defaults: [baseline]
name: both_regularizers_off_no_weight_decay
spatial_model:
  objectives:
    vicreg_encoder:
      variance_weight: 0.0
      covariance_weight: 0.0
  training:
    weight_decay: 0.0
tracking:
  variant_name: both_regularizers_off_no_weight_decay
