defaults: [baseline]
name: both_regularizers_off
spatial_model:
  objectives:
    vicreg_encoder:
      variance_weight: 0.0
      covariance_weight: 0.0
tracking:
  variant_name: both_regularizers_off
