defaults: [baseline]
name: l1_0.003
spatial_model:
  sparsifier:
    type: none
  objectives:
    l1_encoder:
      type: l1_sparsity
      targets: [encoder.place_codes]
      weight: 1.54
tracking:
  variant_name: l1_0.003
