type: slurm
memory_gb: 200
cpus_per_task: 16
exports: {}
job_resources:
  representations:
    cpus_per_task: 4
    memory_gb: 64
    time_hours: 4
  measures:
    gpus: 0
    cpus_per_task: 8
    memory_gb: 64
    time_hours: 24
    omp_num_threads: 4
  navigation:
    cpus_per_task: 8
    memory_gb: 32
    time_hours: 24
  summary:
    gpus: 0
    cpus_per_task: 2
    memory_gb: 8
    time_hours: 2
